package org.jalvarez.stockly.enums;

public enum PurchaseOrderStatus {
    PENDING_APPROVAL, APPROVED, REJECTED,
    OPEN_ORDER, RECEIVED, INVOICED, CANCELLED,
    PENDING_ACKNOWLEDGEMENT, ON_HOLD, UNDELIVERED,
    PARTIALLY_DELIVERED, FULLY_DELIVERED, UNPAID, PAID
}
